version: "3"

services:
    frontend:
        build: frontend/
        ports:
            - 8080:8080
        depends_on:
            - api
    api:
        build: api/
        environment:
            DEBUG: 'true'
    publisher:
        build: publisher/
        environment:
            DEBUG: 'true'
    consumer:
        build: subscriber/
        environment:
            DEBUG: 'true'
    rabbitmq:
        image: rabbitmq:3
        hostname: rabbitmq
    redis:
        image: redis
    postgres:
        image: postgres
        environment: 
            - POSTGRES_USER=helloworld
            - POSTGRES_DB=helloworld_db
        volumes:
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            - ./:/opt/backup    
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - "16686:16686"
            - "5775:5775/udp"