/*
 * CI/CD Dashboard API
 *
 * API for CI/CD Dashboard.
 *
 * API version: 1.0.0
 * Contact: dimitry.ushakov@rackspace.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	service "github.com/dimtruck/opentracing-hello-world/api"
)

func main() {
	log.Printf("Server started")

	router := service.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
